### ISSUE TITLE
Months array defined incorrectly.

### ISSUE THREAD

**Issue by Andrew-Miranti** [dimyr7/ClassScheduler#1]
It is currently defined in Semester.cpp as
`Section::Semester::monthsStr[12] =  {"", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov" "Dec" };`

Two issues:
1) The first month is a blank string.
2) There is no comma between November and December (which probably means we don't get a December).

**Comment by dimyr7** [comment]
Just fixed it
